const COUNTER_KEY = 'surat-sakit-counter'

export function generateLetterNumber(): string {
  const now = new Date()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const year = now.getFullYear()
  const key = `${COUNTER_KEY}-${year}-${month}`
  let counter = 1
  try { const stored = localStorage.getItem(key); if (stored) counter = parseInt(stored, 10) + 1 } catch { /* noop */ }
  try { localStorage.setItem(key, String(counter)) } catch { /* noop */ }
  return `440/${String(counter).padStart(4, '0')}/SKS/${month}/${year}`
}

// Auto-generated city name lookup
const cityNames: Record<string, string> = {
  'kab-aceh-barat': 'Kab. Aceh Barat',
  'kab-aceh-barat-daya': 'Kab. Aceh Barat Daya',
  'kab-aceh-besar': 'Kab. Aceh Besar',
  'kab-aceh-jaya': 'Kab. Aceh Jaya',
  'kab-aceh-selatan': 'Kab. Aceh Selatan',
  'kab-aceh-singkil': 'Kab. Aceh Singkil',
  'kab-aceh-tamiang': 'Kab. Aceh Tamiang',
  'kab-aceh-tengah': 'Kab. Aceh Tengah',
  'kab-aceh-tenggara': 'Kab. Aceh Tenggara',
  'kab-aceh-timur': 'Kab. Aceh Timur',
  'kab-aceh-utara': 'Kab. Aceh Utara',
  'kab-agam': 'Kab. Agam',
  'kab-asahan': 'Kab. Asahan',
  'kab-badung': 'Kab. Badung',
  'kab-balangan': 'Kab. Balangan',
  'kab-banggai-kepulauan': 'Kab. Banggai Kepulauan',
  'kab-banggai-laut': 'Kab. Banggai Laut',
  'kab-bangka-barat': 'Kab. Bangka Barat',
  'kab-bangka-selatan': 'Kab. Bangka Selatan',
  'kab-bangkalan': 'Kab. Bangkalan',
  'kab-bantul': 'Kab. Bantul',
  'kab-banyuasin': 'Kab. Banyuasin',
  'kab-barito-kuala': 'Kab. Barito Kuala',
  'kab-barito-timur': 'Kab. Barito Timur',
  'kab-batu-bara': 'Kab. Batu Bara',
  'kab-bekasi': 'Kab. Bekasi',
  'kab-belitung-timur': 'Kab. Belitung Timur',
  'kab-bener-meriah': 'Kab. Bener Meriah',
  'kab-bengkayang': 'Kab. Bengkayang',
  'kab-bengkulu-selatan': 'Kab. Bengkulu Selatan',
  'kab-bengkulu-tengah': 'Kab. Bengkulu Tengah',
  'kab-berau': 'Kab. Berau',
  'kab-bima': 'Kab. Bima',
  'kab-bintan': 'Kab. Bintan',
  'kab-bireuen': 'Kab. Bireuen',
  'kab-blitar': 'Kab. Blitar',
  'kab-bolaang-mongondow': 'Kab. Bolaang Mongondow',
  'kab-bolaang-mongondow-selatan': 'Kab. Bolaang Mongondow Selatan',
  'kab-bolaang-mongondow-timur': 'Kab. Bolaang Mongondow Timur',
  'kab-bolaang-mongondow-utara': 'Kab. Bolaang Mongondow Utara',
  'kab-bombana': 'Kab. Bombana',
  'kab-bone-bolango': 'Kab. Bone Bolango',
  'kab-bungo': 'Kab. Bungo',
  'kab-buru-selatan': 'Kab. Buru Selatan',
  'kab-buton': 'Kab. Buton',
  'kab-buton-selatan': 'Kab. Buton Selatan',
  'kab-buton-tengah': 'Kab. Buton Tengah',
  'kab-ciamis': 'Kab. Ciamis',
  'kab-cirebon': 'Kab. Cirebon',
  'kab-dairi': 'Kab. Dairi',
  'kab-deli-serdang': 'Kab. Deli Serdang',
  'kab-dharmasraya': 'Kab. Dharmasraya',
  'kab-dogiyai': 'Kab. Dogiyai',
  'kab-empat-lawang': 'Kab. Empat Lawang',
  'kab-flores-timur': 'Kab. Flores Timur',
  'kab-gayo-lues': 'Kab. Gayo Lues',
  'kab-halmahera-barat': 'Kab. Halmahera Barat',
  'kab-halmahera-timur': 'Kab. Halmahera Timur',
  'kab-halmahera-utara': 'Kab. Halmahera Utara',
  'kab-hulu-sungai-utara': 'Kab. Hulu Sungai Utara',
  'kab-humbang-hasundutan': 'Kab. Humbang Hasundutan',
  'kab-indragiri-hulu': 'Kab. Indragiri Hulu',
  'kab-intan-jaya': 'Kab. Intan Jaya',
  'kab-jeneponto': 'Kab. Jeneponto',
  'kab-jepara': 'Kab. Jepara',
  'kab-kampar': 'Kab. Kampar',
  'kab-karanganyar': 'Kab. Karanganyar',
  'kab-karo': 'Kab. Karo',
  'kab-kaur': 'Kab. Kaur',
  'kab-kayong-utara': 'Kab. Kayong Utara',
  'kab-kebumen': 'Kab. Kebumen',
  'kab-kediri': 'Kab. Kediri',
  'kab-keerom': 'Kab. Keerom',
  'kab-kepahiang': 'Kab. Kepahiang',
  'kab-kepulauan-anambas': 'Kab. Kepulauan Anambas',
  'kab-kepulauan-aru': 'Kab. Kepulauan Aru',
  'kab-kepulauan-mentawai': 'Kab. Kepulauan Mentawai',
  'kab-kepulauan-selayar': 'Kab. Kepulauan Selayar',
  'kab-kepulauan-seribu': 'Kab. Kepulauan Seribu',
  'kab-kepulauan-siau-tagulandang-biaro': 'Kab. Kepulauan Siau Tagulandang Biaro',
  'kab-kepulauan-sula': 'Kab. Kepulauan Sula',
  'kab-kepulauan-talaud': 'Kab. Kepulauan Talaud',
  'kab-kerinci': 'Kab. Kerinci',
  'kab-kolaka-timur': 'Kab. Kolaka Timur',
  'kab-kolaka-utara': 'Kab. Kolaka Utara',
  'kab-konawe-kepulauan': 'Kab. Konawe Kepulauan',
  'kab-konawe-utara': 'Kab. Konawe Utara',
  'kab-kuantan-singingi': 'Kab. Kuantan Singingi',
  'kab-kuningan': 'Kab. Kuningan',
  'kab-kupang': 'Kab. Kupang',
  'kab-labuhanbatu': 'Kab. Labuhanbatu',
  'kab-labuhanbatu-selatan': 'Kab. Labuhanbatu Selatan',
  'kab-labuhanbatu-utara': 'Kab. Labuhanbatu Utara',
  'kab-lamandau': 'Kab. Lamandau',
  'kab-lampung-timur': 'Kab. Lampung Timur',
  'kab-langkat': 'Kab. Langkat',
  'kab-lanny-jaya': 'Kab. Lanny Jaya',
  'kab-lebong': 'Kab. Lebong',
  'kab-lembata': 'Kab. Lembata',
  'kab-lima-puluh-kota': 'Kab. Lima Puluh Kota',
  'kab-lingga': 'Kab. Lingga',
  'kab-luwu': 'Kab. Luwu',
  'kab-luwu-timur': 'Kab. Luwu Timur',
  'kab-luwu-utara': 'Kab. Luwu Utara',
  'kab-madiun': 'Kab. Madiun',
  'kab-magelang': 'Kab. Magelang',
  'kab-magetan': 'Kab. Magetan',
  'kab-mahakam-hulu': 'Kab. Mahakam Hulu',
  'kab-malaka': 'Kab. Malaka',
  'kab-maluku-tenggara': 'Kab. Maluku Tenggara',
  'kab-mamberamo-raya': 'Kab. Mamberamo Raya',
  'kab-mamberamo-tengah': 'Kab. Mamberamo Tengah',
  'kab-mamuju-tengah': 'Kab. Mamuju Tengah',
  'kab-mandailing-natal': 'Kab. Mandailing Natal',
  'kab-manggarai-timur': 'Kab. Manggarai Timur',
  'kab-manokwari-selatan': 'Kab. Manokwari Selatan',
  'kab-mappi': 'Kab. Mappi',
  'kab-melawi': 'Kab. Melawi',
  'kab-merangin': 'Kab. Merangin',
  'kab-mesuji': 'Kab. Mesuji',
  'kab-mimika': 'Kab. Mimika',
  'kab-minahasa': 'Kab. Minahasa',
  'kab-minahasa-selatan': 'Kab. Minahasa Selatan',
  'kab-minahasa-tenggara': 'Kab. Minahasa Tenggara',
  'kab-minahasa-utara': 'Kab. Minahasa Utara',
  'kab-mojokerto': 'Kab. Mojokerto',
  'kab-morowali': 'Kab. Morowali',
  'kab-morowali-utara': 'Kab. Morowali Utara',
  'kab-muaro-jambi': 'Kab. Muaro Jambi',
  'kab-muna-barat': 'Kab. Muna Barat',
  'kab-musi-rawas': 'Kab. Musi Rawas',
  'kab-musi-rawas-utara': 'Kab. Musi Rawas Utara',
  'kab-nagan-raya': 'Kab. Nagan Raya',
  'kab-nagekeo': 'Kab. Nagekeo',
  'kab-nduga': 'Kab. Nduga',
  'kab-ngada': 'Kab. Ngada',
  'kab-nias': 'Kab. Nias',
  'kab-nias-barat': 'Kab. Nias Barat',
  'kab-nias-selatan': 'Kab. Nias Selatan',
  'kab-nias-utara': 'Kab. Nias Utara',
  'kab-ogan-ilir': 'Kab. Ogan Ilir',
  'kab-ogan-komering-ilir': 'Kab. Ogan Komering Ilir',
  'kab-ogan-komering-ulu': 'Kab. Ogan Komering Ulu',
  'kab-ogan-komering-ulu-selatan': 'Kab. Ogan Komering Ulu Selatan',
  'kab-padang-lawas': 'Kab. Padang Lawas',
  'kab-padang-lawas-utara': 'Kab. Padang Lawas Utara',
  'kab-padang-pariaman': 'Kab. Padang Pariaman',
  'kab-pakpak-bharat': 'Kab. Pakpak Bharat',
  'kab-pangandaran': 'Kab. Pangandaran',
  'kab-paniai': 'Kab. Paniai',
  'kab-pasaman': 'Kab. Pasaman',
  'kab-pasaman-barat': 'Kab. Pasaman Barat',
  'kab-pasuruan': 'Kab. Pasuruan',
  'kab-pegunungan-arfak': 'Kab. Pegunungan Arfak',
  'kab-pegunungan-bintang': 'Kab. Pegunungan Bintang',
  'kab-pekalongan': 'Kab. Pekalongan',
  'kab-pelalawan': 'Kab. Pelalawan',
  'kab-penukal-abab-lematang-ilir': 'Kab. Penukal Abab Lematang Ilir',
  'kab-pesawaran': 'Kab. Pesawaran',
  'kab-pesisir-barat': 'Kab. Pesisir Barat',
  'kab-pidie': 'Kab. Pidie',
  'kab-pidie-jaya': 'Kab. Pidie Jaya',
  'kab-pulang-pisau': 'Kab. Pulang Pisau',
  'kab-pulau-morotai': 'Kab. Pulau Morotai',
  'kab-pulau-taliabu': 'Kab. Pulau Taliabu',
  'kab-puncak': 'Kab. Puncak',
  'kab-puncak-jaya': 'Kab. Puncak Jaya',
  'kab-purwakarta': 'Kab. Purwakarta',
  'kab-purworejo': 'Kab. Purworejo',
  'kab-raja-ampat': 'Kab. Raja Ampat',
  'kab-rote-ndao': 'Kab. Rote Ndao',
  'kab-sabu-raijua': 'Kab. Sabu Raijua',
  'kab-sambas': 'Kab. Sambas',
  'kab-samosir': 'Kab. Samosir',
  'kab-sampang': 'Kab. Sampang',
  'kab-sarolangun': 'Kab. Sarolangun',
  'kab-sekadau': 'Kab. Sekadau',
  'kab-seluma': 'Kab. Seluma',
  'kab-seram-bagian-barat': 'Kab. Seram Bagian Barat',
  'kab-seram-bagian-timur': 'Kab. Seram Bagian Timur',
  'kab-serang': 'Kab. Serang',
  'kab-serdang-bedagai': 'Kab. Serdang Bedagai',
  'kab-siak': 'Kab. Siak',
  'kab-sidenreng-rappang': 'Kab. Sidenreng Rappang',
  'kab-sidoarjo': 'Kab. Sidoarjo',
  'kab-sigi': 'Kab. Sigi',
  'kab-sijunjung': 'Kab. Sijunjung',
  'kab-simalungun': 'Kab. Simalungun',
  'kab-simeulue': 'Kab. Simeulue',
  'kab-solok': 'Kab. Solok',
  'kab-solok-selatan': 'Kab. Solok Selatan',
  'kab-sorong': 'Kab. Sorong',
  'kab-sukabumi': 'Kab. Sukabumi',
  'kab-sukoharjo': 'Kab. Sukoharjo',
  'kab-sumba-barat': 'Kab. Sumba Barat',
  'kab-sumba-barat-daya': 'Kab. Sumba Barat Daya',
  'kab-sumba-tengah': 'Kab. Sumba Tengah',
  'kab-supiori': 'Kab. Supiori',
  'kab-tambrauw': 'Kab. Tambrauw',
  'kab-tana-tidung': 'Kab. Tana Tidung',
  'kab-tana-toraja': 'Kab. Tana Toraja',
  'kab-tanah-bumbu': 'Kab. Tanah Bumbu',
  'kab-tanah-datar': 'Kab. Tanah Datar',
  'kab-tangerang': 'Kab. Tangerang',
  'kab-tanggamus': 'Kab. Tanggamus',
  'kab-tanjung-jabung-barat': 'Kab. Tanjung Jabung Barat',
  'kab-tanjung-jabung-timur': 'Kab. Tanjung Jabung Timur',
  'kab-tapanuli-selatan': 'Kab. Tapanuli Selatan',
  'kab-tapanuli-tengah': 'Kab. Tapanuli Tengah',
  'kab-tapanuli-utara': 'Kab. Tapanuli Utara',
  'kab-tebo': 'Kab. Tebo',
  'kab-tegal': 'Kab. Tegal',
  'kab-toba': 'Kab. Toba',
  'kab-tolikara': 'Kab. Tolikara',
  'kab-toraja-utara': 'Kab. Toraja Utara',
  'kab-tulang-bawang': 'Kab. Tulang Bawang',
  'kab-tulang-bawang-barat': 'Kab. Tulang Bawang Barat',
  'kab-wakatobi': 'Kab. Wakatobi',
  'kab-waropen': 'Kab. Waropen',
  'kab-way-kanan': 'Kab. Way Kanan',
  'kab-yahukimo': 'Kab. Yahukimo',
  'kab-yalimo': 'Kab. Yalimo',
  'kab-asmat': 'Agats',
  'kab-karangasem': 'Amlapura',
  'kab-tojo-una-una': 'Ampana',
  'kab-konawe-selatan': 'Andolo',
  'kab-bengkulu-utara': 'Arga Makmur',
  'kab-pacitan': 'Arjosari',
  'kab-maybrat': 'Ayamaru',
  'kab-rokan-hilir': 'Bagansiapiapi',
  'kab-bangli': 'Bangli',
  'kab-banjarnegara': 'Banjarnegara',
  'kab-bantaeng': 'Bantaeng',
  'kab-banyuwangi': 'Banyuwangi',
  'kab-hulu-sungai-tengah': 'Barabai',
  'kab-barru': 'Barru',
  'kab-batang': 'Batang',
  'kab-bengkalis': 'Bengkalis',
  'kab-biak-numfor': 'Biak',
  'kab-teluk-bintuni': 'Bintuni',
  'kab-blora': 'Blora',
  'kab-bojonegoro': 'Bojonegoro',
  'kab-bondowoso': 'Bondowoso',
  'kab-boyolali': 'Boyolali',
  'kab-brebes': 'Brebes',
  'kab-bulukumba': 'Bulukumba',
  'kab-barito-selatan': 'Buntok',
  'kab-buol': 'Buol',
  'kab-cianjur': 'Cianjur',
  'kab-bogor': 'Cibinong',
  'kab-cilacap': 'Cilacap',
  'kab-rejang-lebong': 'Curup',
  'kab-deiyai': 'Deiyai',
  'kab-demak': 'Demak',
  'kab-dompu': 'Dompu',
  'kab-donggala': 'Donggala',
  'kab-ende': 'Ende',
  'kab-enrekang': 'Enrekang',
  'kab-fakfak': 'Fakfak',
  'kab-garut': 'Garut',
  'kab-lombok-barat': 'Gerung',
  'kab-gianyar': 'Gianyar',
  'kab-gresik': 'Gresik',
  'kab-lampung-tengah': 'Gunung Sugih',
  'kab-indramayu': 'Indramayu',
  'kab-jember': 'Jember',
  'kab-jombang': 'Jombang',
  'kab-kaimana': 'Kaimana',
  'kab-alor': 'Kalabahi',
  'kab-lampung-selatan': 'Kalianda',
  'kab-hulu-sungai-selatan': 'Kandangan',
  'kab-karawang': 'Karawang',
  'kab-karimun': 'Karimun',
  'kab-katingan': 'Kasongan',
  'kab-timor-tengah-utara': 'Kefamenanu',
  'kab-kendal': 'Kendal',
  'kab-malang': 'Kepanjen',
  'kab-ketapang': 'Ketapang',
  'kab-klaten': 'Klaten',
  'kab-bangka-tengah': 'Koba',
  'kab-kolaka': 'Kolaka',
  'kab-kotabaru': 'Kotabaru',
  'kab-lampung-utara': 'Kotabumi',
  'kab-probolinggo': 'Kraksaan',
  'kab-kapuas': 'Kuala Kapuas',
  'kab-gunung-mas': 'Kuala Kurun',
  'kab-seruyan': 'Kuala Pembuang',
  'kab-kudus': 'Kudus',
  'kab-buton-utara': 'Kulisusu',
  'kab-gorontalo-utara': 'Kwandang',
  'kab-manggarai-barat': 'Labuan Bajo',
  'kab-lahat': 'Lahat',
  'kab-lamongan': 'Lamongan',
  'kab-gorontalo': 'Limboto',
  'kab-lampung-barat': 'Liwa',
  'kab-lumajang': 'Lumajang',
  'kab-banggai': 'Luwuk',
  'kab-majalengka': 'Majalengka',
  'kab-majene': 'Majene',
  'kab-malinau': 'Malinau',
  'kab-mamasa': 'Mamasa',
  'kab-mamuju': 'Mamuju',
  'kab-manokwari': 'Manokwari',
  'kab-pohuwato': 'Marisa',
  'kab-maros': 'Maros',
  'kab-ogan-komering-ulu-timur': 'Martapura',
  'kab-banjar': 'Martapura',
  'kab-maluku-tengah': 'Masohi',
  'kab-sikka': 'Maumere',
  'kab-mempawah': 'Mempawah',
  'kab-merauke': 'Merauke',
  'kab-batang-hari': 'Muara Bulian',
  'kab-muara-enim': 'Muara Enim',
  'kab-barito-utara': 'Muara Teweh',
  'kab-muko-muko': 'Mukomuko',
  'kab-nabire': 'Nabire',
  'kab-buru': 'Namlea',
  'kab-natuna': 'Natuna',
  'kab-jembrana': 'Negara',
  'kab-landak': 'Ngabang',
  'kab-bandung-barat': 'Ngamprah',
  'kab-nganjuk': 'Nganjuk',
  'kab-ngawi': 'Ngawi',
  'kab-nunukan': 'Nunukan',
  'kab-pesisir-selatan': 'Painan',
  'kab-pamekasan': 'Pamekasan',
  'kab-pandeglang': 'Pandeglang',
  'kab-pangkajene-kepulauan': 'Pangkajene',
  'kab-kotawaringin-barat': 'Pangkalan Bun',
  'kab-parigi-moutong': 'Parigi',
  'kab-pasangkayu': 'Pasangkayu',
  'kab-rokan-hulu': 'Pasir Pengaraian',
  'kab-pati': 'Pati',
  'kab-tanah-laut': 'Pelaihari',
  'kab-pemalang': 'Pemalang',
  'kab-penajam-paser-utara': 'Penajam',
  'kab-pinrang': 'Pinrang',
  'kab-polewali-mandar': 'Polewali',
  'kab-ponorogo': 'Ponorogo',
  'kab-poso': 'Poso',
  'kab-lombok-tengah': 'Praya',
  'kab-pringsewu': 'Pringsewu',
  'kab-purbalingga': 'Purbalingga',
  'kab-murung-raya': 'Puruk Cahu',
  'kab-grobogan': 'Purwodadi',
  'kab-banyumas': 'Purwokerto',
  'kab-kapuas-hulu': 'Putussibau',
  'kab-muna': 'Raha',
  'kab-lebak': 'Rangkasbitung',
  'kab-tapin': 'Rantau',
  'kab-rembang': 'Rembang',
  'kab-manggarai': 'Ruteng',
  'kab-kotawaringin-timur': 'Sampit',
  'kab-kutai-timur': 'Sangatta',
  'kab-sanggau': 'Sanggau',
  'kab-sarmi': 'Sarmi',
  'kab-kepulauan-tanimbar': 'Saumlaki',
  'kab-musi-banyuasin': 'Sekayu',
  'kab-kepulauan-meranti': 'Selat Panjang',
  'kab-lombok-timur': 'Selong',
  'kab-klungkung': 'Semarapura',
  'kab-kutai-barat': 'Sendawar',
  'kab-wajo': 'Sengkang',
  'kab-jayapura': 'Sentani',
  'kab-kepulauan-yapen': 'Serui',
  'kab-tasikmalaya': 'Singaparna',
  'kab-buleleng': 'Singaraja',
  'kab-sinjai': 'Sinjai',
  'kab-sintang': 'Sintang',
  'kab-situbondo': 'Situbondo',
  'kab-sleman': 'Sleman',
  'kab-halmahera-tengah': 'Soa Ahu',
  'kab-halmahera-selatan': 'Soa Siu',
  'kab-timor-tengah-selatan': 'Soe',
  'kab-bandung': 'Soreang',
  'kab-sragen': 'Sragen',
  'kab-subang': 'Subang',
  'kab-sukamara': 'Sukamara',
  'kab-sumbawa': 'Sumbawa Besar',
  'kab-sumedang': 'Sumedang',
  'kab-sumenep': 'Sumenep',
  'kab-kubu-raya': 'Sungai Ambawang',
  'kab-bangka': 'Sungailiat',
  'kab-gowa': 'Sungguminasa',
  'kab-tabanan': 'Tabanan',
  'kab-kepulauan-sangihe': 'Tahuna',
  'kab-takalar': 'Takalar',
  'kab-sumbawa-barat': 'Taliwang',
  'kab-paser': 'Tanah Grogot',
  'kab-boven-digoel': 'Tanah Merah',
  'kab-lombok-utara': 'Tanjung',
  'kab-tabalong': 'Tanjung',
  'kab-belitung': 'Tanjung Pandan',
  'kab-bulungan': 'Tanjung Selor',
  'kab-temanggung': 'Temanggung',
  'kab-indragiri-hilir': 'Tembilahan',
  'kab-sorong-selatan': 'Teminabuan',
  'kab-kutai-kartanegara': 'Tenggarong',
  'kab-maluku-barat-daya': 'Tiakur',
  'kab-boalemo': 'Tilamuta',
  'kab-toli-toli': 'Tolitoli',
  'kab-trenggalek': 'Trenggalek',
  'kab-tuban': 'Tuban',
  'kab-tulungagung': 'Tulungagung',
  'kab-konawe': 'Unaaha',
  'kab-semarang': 'Ungaran',
  'kab-sumba-timur': 'Waingapu',
  'kab-jayawijaya': 'Wamena',
  'kab-teluk-wondama': 'Wasior',
  'kab-bone': 'Watampone',
  'kab-soppeng': 'Watansoppeng',
  'kab-kulon-progo': 'Wates',
  'kab-wonogiri': 'Wonogiri',
  'kab-gunung-kidul': 'Wonosari',
  'kab-wonosobo': 'Wonosobo',
  'kota-jakarta-barat': 'Jakarta Barat',
  'kota-jakarta-pusat': 'Jakarta Pusat',
  'kota-jakarta-selatan': 'Jakarta Selatan',
  'kota-jakarta-timur': 'Jakarta Timur',
  'kota-jakarta-utara': 'Jakarta Utara',
  'kota-ambon': 'Ambon',
  'kota-balikpapan': 'Balikpapan',
  'kota-banda-aceh': 'Banda Aceh',
  'kota-bandar-lampung': 'Bandar Lampung',
  'kota-bandung': 'Bandung',
  'kota-banjar': 'Banjar',
  'kota-banjarbaru': 'Banjarbaru',
  'kota-banjarmasin': 'Banjarmasin',
  'kota-batam': 'Batam',
  'kota-batu': 'Batu',
  'kota-baubau': 'Baubau',
  'kota-bekasi': 'Bekasi',
  'kota-bengkulu': 'Bengkulu',
  'kota-bima': 'Bima',
  'kota-binjai': 'Binjai',
  'kota-bitung': 'Bitung',
  'kota-blitar': 'Blitar',
  'kota-bogor': 'Bogor',
  'kota-bontang': 'Bontang',
  'kota-bukittinggi': 'Bukittinggi',
  'kota-cilegon': 'Cilegon',
  'kota-cimahi': 'Cimahi',
  'kota-cirebon': 'Cirebon',
  'kota-denpasar': 'Denpasar',
  'kota-depok': 'Depok',
  'kota-durai': 'Dumai',
  'kota-gorontalo': 'Gorontalo',
  'kota-gunungsitoli': 'Gunungsitoli',
  'kota-jambi': 'Jambi',
  'kota-jayapura': 'Jayapura',
  'kota-kediri': 'Kediri',
  'kota-kendari': 'Kendari',
  'kota-kotamobagu': 'Kotamobagu',
  'kota-kupang': 'Kupang',
  'kota-langsa': 'Langsa',
  'kota-lhokseumawe': 'Lhokseumawe',
  'kota-lubuklinggau': 'Lubuklinggau',
  'kota-madiun': 'Madiun',
  'kota-magelang': 'Magelang',
  'kota-makassar': 'Makassar',
  'kota-malang': 'Malang',
  'kota-manado': 'Manado',
  'kota-mataram': 'Mataram',
  'kota-medan': 'Medan',
  'kota-metro': 'Metro',
  'kota-mojokerto': 'Mojokerto',
  'kota-padang': 'Padang',
  'kota-padang-panjang': 'Padang Panjang',
  'kota-padangsidempuan': 'Padangsidempuan',
  'kota-pagar-alam': 'Pagar Alam',
  'kota-palangka-raya': 'Palangka Raya',
  'kota-palembang': 'Palembang',
  'kota-palopo': 'Palopo',
  'kota-palu': 'Palu',
  'kota-pangkal-pinang': 'Pangkal Pinang',
  'kota-parepare': 'Parepare',
  'kota-pariaman': 'Pariaman',
  'kota-pasuruan': 'Pasuruan',
  'kota-payakumbuh': 'Payakumbuh',
  'kota-pekalongan': 'Pekalongan',
  'kota-pekanbaru': 'Pekanbaru',
  'kota-pematangsiantar': 'Pematangsiantar',
  'kota-pontianak': 'Pontianak',
  'kota-prabumulih': 'Prabumulih',
  'kota-probolinggo': 'Probolinggo',
  'kota-sabang': 'Sabang',
  'kota-salatiga': 'Salatiga',
  'kota-samarinda': 'Samarinda',
  'kota-sawahlunto': 'Sawahlunto',
  'kota-semarang': 'Semarang',
  'kota-serang': 'Serang',
  'kota-sibolga': 'Sibolga',
  'kota-singkawang': 'Singkawang',
  'kota-surakarta': 'Solo / Surakarta',
  'kota-solok': 'Solok',
  'kota-sorong': 'Sorong',
  'kota-subulussalam': 'Subulussalam',
  'kota-sukabumi': 'Sukabumi',
  'kota-sungai-penuh': 'Sungai Penuh',
  'kota-surabaya': 'Surabaya',
  'kota-tangerang': 'Tangerang',
  'kota-tangerang-selatan': 'Tangerang Selatan',
  'kota-tanjung-pinang': 'Tanjung Pinang',
  'kota-tanjungbalai': 'Tanjungbalai',
  'kota-tarakan': 'Tarakan',
  'kota-tasikmalaya': 'Tasikmalaya',
  'kota-tebing-tinggi': 'Tebing Tinggi',
  'kota-tegal': 'Tegal',
  'kota-ternate': 'Ternate',
  'kota-tidore-kepulauan': 'Tidore Kepulauan',
  'kota-tomohon': 'Tomohon',
  'kota-tual': 'Tual',
  'kota-yogyakarta': 'Yogyakarta',
}

export function getCityName(cityId: string): string {
  return cityNames[cityId] || cityId
}

export function formatDate(dateStr: string): string {
  if (!dateStr) return '-'
  const d = new Date(dateStr)
  return d.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })
}

export function getDayDifference(start: string, end: string): number {
  const s = new Date(start), e = new Date(end)
  return Math.max(1, Math.ceil((e.getTime() - s.getTime()) / (1000 * 60 * 60 * 24)))
}
